---
abstract: 'asynchronous ssh command invocation '
author:
  - 'Nick Stokoe <wulee@cpan.org>'
build_requires:
  Config: 0
  English: 0
  File::Find: 0
  FindBin: 0
  Getopt::Long: 0
  Module::Build: 0.2808
  Pod::Coverage::TrustPod: 0
  Test::More: 0
  Text::ParseWords: 0
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0.2808
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SSH-Mechanize
recommends:
  Term::ReadKey: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  AnyEvent: 0
  AnyEvent::Subprocess: 0
  AnyEvent::Subprocess::Running: 0
  Carp: 0
  Coro: 0
  Moose: 0
  MooseX::Params::Validate: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-SSH-Mechanize
  repository: git://github.com/wu-lee/Net-SSH-Mechanize.git
version: 0.1.3
