---
abstract: 'Asynchronous ssh command invocation'
author:
  - 'Nick Stokoe <wulee@cpan.org>'
build_requires:
  Module::Build: 0.28
configure_requires:
  Module::Build: 0.28
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112580'
keywords:
  - anyevent
  - ssh
  - coro
  - sudo
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SSH-Mechanize
provides:
  Net::SSH::Mechanize:
    file: lib/Net/SSH/Mechanize.pm
    version: v0.1.1
  Net::SSH::Mechanize::ConnectParams:
    file: lib/Net/SSH/Mechanize/ConnectParams.pm
    version: 0
  Net::SSH::Mechanize::Multi:
    file: lib/Net/SSH/Mechanize/Multi.pm
    version: 0
  Net::SSH::Mechanize::Session:
    file: lib/Net/SSH/Mechanize/Session.pm
    version: 0
recommends:
  Term::ReadKey: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
requires:
  AnyEvent: 0
  AnyEvent::Subprocess: 0
  Coro: 0
  Moose: 0
  MooseX::Params::Validate: 0
  Test::More: 0
  version: 0.77
resources:
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://github.com/wu-lee/Net-SSH-Mechanize
version: v0.1.1
